### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by redmag3** [DevotedMC/CastleGates#11]
Not an Issue, feature request, but github is scary and confusing to me.

Is there a way that castle gates can grab rails attached to the blocks removed or added to the gate?

for example

```
  _  _  _  _ 
```

[G][B][B][B][B][G]

where dashes are rails, [G] are gearblocks and [B] are regular blocks

Hopefully the castlegate can take the rails with it when it retracts, and place them when it extends, if this was possible you could have detector rails over the gearblock to activate it ... such devious traps could be made, or minecart diversionary paths... muhahaha

**Comment by Aleksey-Terzi** [comment]
You can implement this behavior if rail will serve as usual Bridge Block.
By default config doesn't allow this, therefore you should add rails to plugin's config as blocks allowed for Bridge and for Gearblock

Then:

1) Put your railroad bridge built from regular blocks, mark gearblocks and put bridge between them

2) Do the same with rails above the regular blocks

3) Integration with jukealert would allow you to retract bridge with rails when "enemy" will appears, look wiki for details

PS. Insidious idea :)

PSS. Sorry for late response, just now found - I'm not on the watch for this fork!

**Comment by redmag3** [comment]
Cool, ty!

**Comment by Aleksey-Terzi** [comment]
I'm supposing request could be closed?
