### ISSUE TITLE
Question from modmail reg. grass

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/CastleGates#12]
> Is it intended behavior for castlegates to break if grass is used as the block between them?

**Comment by Aleksey-Terzi** [comment]
By default grass is not in the config, but I could be added.
Also with grass could happen "interesting" thing - player put dirt block as bridge and it is working, then after some time dirt is converting to grass and bridge is stopping to work.

Sorry for late response, I forgot to add myself to watch list!

**Comment by Aleksey-Terzi** [comment]
I'm supposing issue is solved.
Can you please close issue?
