### ISSUE TITLE
Trouble getting CastleGate length

### ISSUE THREAD

**Issue by Epsilon29** [DevotedMC/CastleGates#20]
http://i.imgur.com/eE458tY.png
Players found CastleGates to stop working after a restart. Error came out everytime the players attempted to trigger castlegate. For reference CastleGate was only 4 blocks long. Double checked config and it was set to the default 16 block length for the bridge.

**Comment by Aleksey-Terzi** [comment]
Looks like error related to Orebfuscator.  
Could you please provide:  
1) What version of Orebfuscator are you using?
2) Orebfuscator's config file
3) List/names of all worlds on the servers

**Comment by Aleksey-Terzi** [comment]
I'm supposing issue is not actual anymore, could it be closed?
