### ISSUE TITLE
Begin Timer function only after redstone signal is lost

### ISSUE THREAD

**Issue by Diet-Cola** [DevotedMC/CastleGates#23]
Possibly add ability for Timer function to begin after the gearblock has lost power.  

Achievable by doing something along the lines of:
/cg timer 1 UNDRAW off

The idea behind it would be:
/cg timer [time] [draw/undraw/revert] [auto trigger on/off]  

Current behaviour should probably be retained as default unless "off" is specified at the end.  

Ofcourse this is just my idea, any alternative methods that may help this are ofcourse welcomed.

**Comment by iykHvfIvfR** [comment]
Added in https://github.com/DevotedMC/CastleGates/pull/24

@ProgrammerDan good to close right?
