### ISSUE TITLE
Timer for revert state

### ISSUE THREAD

**Issue by Aleksey-Terzi** [DevotedMC/CastleGates#9]
What we have now - when player is powering gearblock:

1) It is changing state (open/close gates)

2) State cannot be changed more than once per 1 second (could be changed in config Settings.SwitchTimeout)

What I propose - allow for player to set timer for revert state.

For example:

1) I could set timer to 3 seconds for gearblock

2) When I activating gearblock - it is opening gates

3) During 3 second gates' state cannot be changed (i.e. gates stay opened min 3 seconds)

4) After 3 seconds passed - gearblock will be activated by timer and gates will be closed

5) About Citadel and Bastion - permissions will be checked at step 2 (where gearblock was activated by player). Player must have permissions for both"draw" and "undraw" operations. If haven't - then timer will not be activated. Also timer will remember all gates' blocks and if structure will change on "alert" time then timer will fail to do activation.

Why this feature is needed - automatically close gates/doors/bridges/traps.
For example I could put pressure plate/button to activate my gates and timer will make sure gates closed after some time (like we have with doors)

Timer could be set using command (exact time) or via GUI (some predefined intervals)

We could make timer as default feature of gerablock or maybe gearblock should be improved more (for example by consuming redstone block) to allow timer usage.

Please let me know your opinions. @ProgrammerDan, @ShadedJon

**Comment by ProgrammerDan** [comment]
I'd be good with this, sounds great.

**Comment by PromoFaux** [comment]
@Aleksey-Terzi Would the player still need to be in range of the gearblock for the state to revert?

i.e At the moment I have a castlegate set up over a very deep drop. I ended up setting up a redstone timer to close the gate after a couple of seconds. If I am stood on the CG when I press the button, I will drop into the hole as intended, however unless I slow my fall (with a couple of layers of water at the top for example) the gate will not close again, even though the redstone fires. It will only close if I/someone else on the citadel group is stood within range of the gearblock.

**Comment by Aleksey-Terzi** [comment]
@PromoFaux 

> Would the player still need to be in range of the gearblock for the state to revert?

It is supposed that "state revert" could be done even if "group member" is not in range.

> It will only close if I/someone else on the citadel group is stood within range of the gearblock.

This probably could be solved in the following way (if you ok that anyone not in group could close gate):

1) put JukeAlert with gearblock's Citadel group in the range from gearblock (8 blocks by default)

2) Enable "lever triggering" for this JukeAlert (on Devoted this feature is enabled - I tested)

For details and video look here: https://github.com/Aleksey-Terzi/CastleGates/wiki#interaction-with-jukealert-plugin

**Comment by Aleksey-Terzi** [comment]
Implemented.
Details are here: https://github.com/Aleksey-Terzi/CastleGates/wiki#timer
